# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cards',
                'doc_host': 'https://seeM.github.io',
                'git_url': 'https://github.com/seeM/cards',
                'lib_path': 'cards'},
  'syms': {'cards.core': {'cards.core.foo': ('core.html#foo', 'cards/core.py')}}}
