# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 2
from .card import Card

import random
from collections.abc import MutableSequence

# %% ../nbs/01_deck.ipynb 5
class Deck(MutableSequence):
    def __init__(self):
        self.cards = []
        for suit in range(4):
            for rank in range(1, 14):
                card = Card(suit, rank)
                self.cards.append(card)
                
    def __getitem__(self, key):
        return self.cards[key]
    
    def __setitem__(self, key, value):
        self.cards[key] = value
    
    def __delitem__(self, key):
        del self.cards[key]
    
    def __len__(self):
        return len(self.cards)
    
    def insert(self, key, value):
        self.cards.insert(key, value)
        
    def shuffle(self):
        random.shuffle(self.cards)
                
    def __repr__(self):
        return ' '.join(repr(card) for card in self.cards)
